apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  artifactRepository: |
   archiveLogs: false
   s3:
     endpoint: demo-minio:9000
     bucket: demo
     insecure: true
     keyPrefix: artifacts
     accessKeySecret:
       name: demo-minio
       key: accesskey
     secretKeySecret:
       name: demo-minio
       key: secretkey